# Generated by Django 5.0.3 on 2024-03-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('have_tried', models.TextField()),
                ('created_date', models.DateTimeField(verbose_name='Created on')),
            ],
        ),
    ]
